name: range-90d

on:
  workflow_dispatch:
    inputs:
      from:
        description: "IATA origem"
        required: true
        default: "GYN"
      to:
        description: "IATA destino"
        required: true
        default: "CAC"
      days:
        description: "Dias para frente (a partir de hoje)"
        required: true
        default: "90"
      delay_ms:
        description: "Pausa entre dias (ms)"
        required: true
        default: "4000"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # necessário pro commit automático

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: |
          npm ci || npm i

      - name: Instalar browsers do Playwright
        run: npx playwright install --with-deps

      - name: Rodar varredura (dia a dia)
        run: |
          node run-range.cjs --from "${{ inputs.from }}" --to "${{ inputs.to }}" --days "${{ inputs.days }}" --delay-ms "${{ inputs.delay_ms }}"

      - name: Commit e push dos dados gerados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "data: ${{ inputs.from }}-${{ inputs.to }} (run ${{ github.run_number }})"
          file_pattern: |
            data/**
            public/results.csv

      # opcional: também disponibiliza download como artefato
      - name: Upload artifact (opcional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data-${{ inputs.from }}-${{ inputs.to }}-${{ github.run_number }}
          path: |
            data/**
            public/results.csv
          if-no-files-found: warn
          retention-days: 7
